# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Renu Sharma"                                # Your name
  description: "Renu is PhD candidate in Marketing at University of Houston"   # A brief slogan (optional)
  image: img/my_image.jpg
  site-url: "https://sharma-renu.github.io"  # Add your website URL This creates sitemap xml file
  
  # favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    #pinned: true
    # logo: /img/logo.png
    
    # your sub-pages
    right:
      - text: "Research"
        href: research/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "CV"
        href: cv/index.qmd

 # start of the navigation bar on top left of the website    
    # your social media handles
    # left:
      # - icon: folder-symlink
      #   href: https://www.marvinschmitt.com/blog/website-tutorial-quarto/
      # - icon: twitter
      #   href: https://twitter.com/MarvinSchmittML
      # - icon: linkedin
      #   href: https://www.linkedin.com/in/praveen-punia/
      # - icon: envelope
      #   aria-label: email
      #   href: "mailto:praveen_punia@outlook.com"  
  
  

# Don't touch unless you know what you are doing :) ------------
 # Uncomment the following lines to enable search
  # search: 
  #   location: navbar 
  #   type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2026 Renu Sharma CC BY-SA 4.0</span>
    # center: |
    #   <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    # right: |
    #   <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs
  resources:
    - googleea7a7eed59362a5f.html
    - sitemap.xml 
    
    
  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true